databases:
  - name: in-4cus_DB
    databaseName: in_4cus_db
    user: in 4cus
    region: singapore

services: in 4cus
  - type: web
    name: 
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: in-4cus_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

